### ISSUE TITLE
For Spree 0.9.99

### ISSUE THREAD

**Issue by tekknikk** [tonkapark/spree-wordsmith#1]
create file wordsmith_hooks.rb @ extension root with:

class WordsmithHooks < Spree::ThemeSupport::HookListener
    insert_after :admin_tabs do
    %(<%=  tab(:wordsmith , { :label => t("Wordsmith"), :route => :admin_posts })  %>) 
  end
end

**Comment by bfkelsey** [comment]
You also need to comment this out in wordsmith_extension.rb :

Admin::BaseController.class_eval do
      before_filter :add_wordsmith_tab
    #
      def add_wordsmith_tab
    # # add_extension_admin_tab takes an array containing the same arguments expected
    # # by the tab helper method:
    # # [ :extension_name, { :label => "Your Extension", :route => "/some/non/standard/route" } ]
        add_extension_admin_tab [ :wordsmith, { :label => t("Wordsmith"), :route => :admin_posts } ]
      end
    end

**Comment by jetblackstar** [comment]
Re-formatted tekknikk's code block, slipped out of the Markdown syntax me thinks :)

```
class WordsmithHooks < Spree::ThemeSupport::HookListener
  insert_after :admin_tabs do
    %(<%=  tab(:wordsmith , { :label => t("Wordsmith"), :route => :admin_posts })  %>) 
  end
end
```

**Comment by branch14** [comment]
You might also want to get rid of the following code in wordsmith_extension.rb or your admin users view won't render.

```
# TODO: Not sure I like this solution for the long term because you cannot control placement in view.
Admin::UsersController.class_eval do
  before_filter :add_display_name_field
  def add_display_name_field
@extension_partials << 'display_name'
  end
end
```

**Comment by branch14** [comment]
And add this to wordsmith_hooks.rb

```
insert_after :admin_user_form_fields do
  %(<%= render :partial => 'display_name', :locals => {:f => f}  %>)
end
```

**Comment by tonkapark** [comment]
I finally took all the comments and implemented the changes. Thanks guys.  Does this get things working for you now?
